apiVersion: v1
data:
    token: ENC[AES256_GCM,data:7pmCtHdGOlgh8g==,iv:Q5CuoUhR32mFOgKKgD4KI6yzu8c/VJAlzMDDtiOnLF4=,tag:U2zqyDzsSPCcG7JWDaQhFA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot
    namespace: demo
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/devops-prom/locations/global/keyRings/sops-flux2/cryptoKeys/sops-key-flux
          created_at: "2024-01-21T23:38:04Z"
          enc: CiQA7rhpbr35w0dHbctmiyzOTzTI39eX8QTcMHEWH8K9nP1xzN0SSQDGlDWmHLKdrhIsKljhK8pbMFHIsMT177cLMmB/o/wSpX4jZsEIg5wGjPva1/ncucDOz0JfSxUt1yuP7zatSTiuAkaJSN5bQn0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-21T23:38:04Z"
    mac: ENC[AES256_GCM,data:VQT6ZAX6M0h4q8ULvw9ZO289QkivXK/0pfZYMcFSmstzNwE7yylKvqTIvQo6lT8QHIJ5C5OUoDQZLaPjdDsO+YYfg2SQqPEkhbZayGDQAcQ+aeSjMZRcdHVvNzOzmF2Oj8X98b0QLUOlIHzkOCEB7t9b4+rYrvs897pj+8hiH1g=,iv:tHy/IiNGlLxEA98KmknyKXUC0Aay9J/QdXgCdxrpfBI=,tag:HDc/LEZqYUUL0MypTX1zaA==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.8.1
