name: Update Secrets

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'clusters/demo/secret.yml'

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up SOPS
        run: |
          wget -qO- https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64 > sops
          chmod +x sops
          sudo mv sops /usr/local/bin/
          echo $PATH $PWD
    
      - name: Retrieve Secret from GCP Secret Manager
        run: |
          export TELE_TOKEN=$(gcloud secrets versions access 1 --secret=TELE_TOKEN)

      - name: Update Image Tag
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.data.token=$TELE_TOKEN' clusters/demo/secret.yml

      - name: Decrypt and Update Secrets
        run: |
          sops -e -gcp-kms projects/devops-prom/locations/global/keyRings/sops-flux2/cryptoKeys/sops-key-flux --encrypted-regex '^(token)$' clusters/demo/secret.yml > clusters/demo/secret-enc.yaml
          
      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add clusters/demo/secret-enc.yaml
          git commit -m "Update secret-enc.yaml"
          git push
