name: Update Secrets

on:
  push:
    branches:
      - main

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up SOPS
        run: |
          wget -qO- https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64 > sops
          chmod +x sops
          sudo mv sops /usr/local/bin/
          echo $PATH $PWD

      - name: Update Image Tag
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.data.token=$TELE_TOKEN' clusters/demo/secret.yaml

      - name: Decrypt and Update Secrets
        run: |
          sops -e -gcp-kms projects/devops-prom/locations/global/keyRings/sops-flux2/cryptoKeys/sops-key-flux --encrypted-regex '^(token)$' clusters/demo/secret.yaml > clusters/demo/secret-enc1.yaml
          
      - name: Commit Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add clusters/demo/secre-enc1.yaml
          git commit -m "Update secret-enc1.yaml"
          git push
